runtime: custom
env: flex
service: visits

network:
  forwarded_ports:
    - 80:8080

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 3
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5

env_variables:
  FIREBASE_API_KEY: 'AIzaSyDUqBlFZQj7hJK60nbCrFohlW8t35vo_QE'
  GOOGLE_PROJECT_ID: 'sestro-165123'
  FIREBASE_URL: 'https://sestro-165123.firebaseio.com'
  APP_HOST_SCHEME: 'http'
  APP_HOST: 'api.sestro.io'
  APP_HOST_PORT: '80'
  REDIS_ADDR: 'redis-11053.c1.us-central1-2.gce.cloud.redislabs.com:11053'
  REDIS_PASSSWORD: 'FlyingCar2017'